[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "euler-evc/=lib/euler-evc/src/",
    "erc4626-tests/=lib/erc4626-tests/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

[profile.default.fuzz]
seed = "0xee1d0f7d9556539a9c0e26aed5e63557"

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "preserve"
override_spacing = true
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
